apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesense-backend
  labels:
    service: moviesense-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: moviesense-backend
  template:
    metadata:
      labels:
        service: moviesense-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Postgres..."
              until nc -z postgreaccount 5432; do
                echo "Postgres not ready, sleeping...";
                sleep 2;
              done
              echo "Postgres is up!"
      containers:
        - name: moviesense-backend
          image: "{{ .Values.images.backend.name }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.moviesensebackend.targetPort }}
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      restartPolicy: Always
