apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-sense-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Optional: If your backend needs to strip a path prefix, use this:
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    # Rule for the Frontend
    - host: moviesense.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moviesense-frontend
                port:
                  number: 80
    # Rule for the Backend
    - host: moviesense-backend
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moviesense-backend
                port:
                  number: 8081
