apiVersion: v1
kind: Service
metadata:
  name: moviesense-backend
  labels:
    app: moviesense-backend
spec:
  type: NodePort
  selector:
    service: moviesense-backend
  ports:
    - name: http
      port: 8000 # service port (frontend will call this)
      targetPort: 8000 # actual containerPort from Deployment

